Remove call of 'python setup.py testr' in tox.ini
Because we do not have a .testr.conf configuration file the call of
python setup.py testr will fail.

---snip---
py27 runtests: commands[0] | python setup.py testr --slowest --testr-args=docs
running testr
No .testr.conf config file
error: testr failed (3)
---snap---

Change-Id: I0535bd86e102af7f1c39e4f55d9abf281e55af04